2024-10-01 20:03:16,313 - itchat - ERROR - Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=jGfR67817KKiJ5Pj&skey=@crypt_97de4bb_10cdbb594df6fcf1dba42e040e82290e&pass_ticket=7BU5cB8HJcM5E3DLPQngj6wr7m0a2OTGnG%2BgErxfoQs28wTzM7Yh8AbqSSRbDWTUFs%2F6t%2FDsUYauGOnWfWnAhQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 301, in maintain_loop
    msgList, contactList = self.get_msg()
                           ^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 390, in get_msg
    r = self.s.post(url, data=json.dumps(data),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=jGfR67817KKiJ5Pj&skey=@crypt_97de4bb_10cdbb594df6fcf1dba42e040e82290e&pass_ticket=7BU5cB8HJcM5E3DLPQngj6wr7m0a2OTGnG%2BgErxfoQs28wTzM7Yh8AbqSSRbDWTUFs%2F6t%2FDsUYauGOnWfWnAhQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

2024-10-01 20:03:18,016 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/47048853.html#10 牛郎织女（一）课件-2024-2025学年语文五年级上册统编版
2024-10-01 20:03:18,016 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/47048853.html']
2024-10-01 20:03:18,016 - root - INFO - 打开URL: https://m.zxxk.com/soft/47048853.html
2024-10-01 20:03:18,174 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/47670180.html#11 牛郎织女（二）课件-2024-2025学年语文五年级上册统编版
2024-10-01 20:03:18,174 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/47670180.html']
2024-10-01 20:03:18,174 - root - INFO - 打开URL: https://m.zxxk.com/soft/47670180.html
2024-10-01 20:03:41,593 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/11+牛郎织女（二）课件-2024-2025学年语文五年级上册统编版.pptx
2024-10-01 20:03:46,610 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/11+牛郎织女（二）课件-2024-2025学年语文五年级上册统编版.pptx
2024-10-01 20:03:51,618 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/11+牛郎织女（二）课件-2024-2025学年语文五年级上册统编版.pptx, 准备上传
2024-10-01 20:03:51,618 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/11+牛郎织女（二）课件-2024-2025学年语文五年级上册统编版.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:03:56,410 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:04:11,540 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/10+牛郎织女（一）课件-2024-2025学年语文五年级上册统编版.pptx
2024-10-01 20:04:17,565 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/10+牛郎织女（一）课件-2024-2025学年语文五年级上册统编版.pptx
2024-10-01 20:04:22,571 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/10+牛郎织女（一）课件-2024-2025学年语文五年级上册统编版.pptx, 准备上传
2024-10-01 20:04:22,572 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/10+牛郎织女（一）课件-2024-2025学年语文五年级上册统编版.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:04:25,114 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:06:21,367 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/42022186.html
2024-10-01 20:06:21,369 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/42022186.html']
2024-10-01 20:06:21,369 - root - INFO - 打开URL: https://www.zxxk.com/soft/42022186.html
2024-10-01 20:06:34,441 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第七单元+第1课++《+温度》+分层作业-【随课练】四年级数学上册同步高效练习++北师大版.docx
2024-10-01 20:06:40,463 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第七单元+第1课++《+温度》+分层作业-【随课练】四年级数学上册同步高效练习++北师大版.docx
2024-10-01 20:06:45,467 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第七单元+第1课++《+温度》+分层作业-【随课练】四年级数学上册同步高效练习++北师大版.docx, 准备上传
2024-10-01 20:06:45,467 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第七单元+第1课++《+温度》+分层作业-【随课练】四年级数学上册同步高效练习++北师大版.docx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:06:46,866 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:11:49,183 - itchat - ERROR - Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1727784703927&skey=%40crypt_97de4bb_10cdbb594df6fcf1dba42e040e82290e&sid=jGfR67817KKiJ5Pj&uin=3061080437&deviceid=e464999985527647&synckey=1_807022434%7C2_806993524%7C3_807024323%7C11_807022431%7C23_1727774297%7C24_1727784703%7C25_806993524%7C27_1653909%7C201_1727784703%7C202_1727779562%7C206_103%7C1000_1727782802%7C1001_1727782862&_=1727774297385 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 356, in sync_check
    r = self.s.get(url, params=params, headers=headers,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1727784703927&skey=%40crypt_97de4bb_10cdbb594df6fcf1dba42e040e82290e&sid=jGfR67817KKiJ5Pj&uin=3061080437&deviceid=e464999985527647&synckey=1_807022434%7C2_806993524%7C3_807024323%7C11_807022431%7C23_1727774297%7C24_1727784703%7C25_806993524%7C27_1653909%7C201_1727784703%7C202_1727779562%7C206_103%7C1000_1727782802%7C1001_1727782862&_=1727774297385 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 295, in maintain_loop
    i = sync_check(self)
        ^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 360, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
                      ~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range

2024-10-01 20:24:43,177 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47634919.html
2024-10-01 20:24:43,179 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47634919.html']
2024-10-01 20:24:43,179 - root - INFO - 打开URL: https://www.zxxk.com/soft/47634919.html
2024-10-01 20:24:52,155 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47671146.html
2024-10-01 20:24:52,156 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47671146.html']
2024-10-01 20:24:52,157 - root - INFO - 打开URL: https://www.zxxk.com/soft/47671146.html
2024-10-01 20:24:52,689 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/Unit+3+Amazing+animals（同步练）-2024-2025学年人教PEP版（2024）英语三年级上册.docx
2024-10-01 20:24:58,714 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/Unit+3+Amazing+animals（同步练）-2024-2025学年人教PEP版（2024）英语三年级上册.docx
2024-10-01 20:25:03,717 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/Unit+3+Amazing+animals（同步练）-2024-2025学年人教PEP版（2024）英语三年级上册.docx, 准备上传
2024-10-01 20:25:03,718 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/Unit+3+Amazing+animals（同步练）-2024-2025学年人教PEP版（2024）英语三年级上册.docx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:25:04,807 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:27:24,824 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/Unit+3+Amazing+animals（课件）-2024-2025学年人教PEP版（2024）英语三年级上册+.pptx
2024-10-01 20:27:29,837 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/Unit+3+Amazing+animals（课件）-2024-2025学年人教PEP版（2024）英语三年级上册+.pptx
2024-10-01 20:27:34,843 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/Unit+3+Amazing+animals（课件）-2024-2025学年人教PEP版（2024）英语三年级上册+.pptx, 准备上传
2024-10-01 20:27:34,847 - root - WARNING - 文件大小 74471827 字节 超过企业微信限制的 52428800 字节。
2024-10-01 20:27:34,847 - root - ERROR - 未配置云上传器，无法分享文件链接。
2024-10-01 20:37:22,132 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: 「穿着Parada的007💋💋：https://www.zxxk.com/soft/47671146.html」
- - - - - - - - - - - - - - -
这个下载了吗？@李老师
2024-10-01 20:37:22,135 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47671146.html」']
2024-10-01 20:37:22,135 - root - INFO - 打开URL: https://www.zxxk.com/soft/47671146.html」
2024-10-01 20:37:49,482 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: @李老师呀 
2024-10-01 20:37:49,483 - root - INFO - 识别到URL: []
2024-10-01 20:38:12,822 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: 超过 25MB 的程序无法自动上传
2024-10-01 20:38:12,823 - root - INFO - 识别到URL: []
2024-10-01 20:38:29,378 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: 等 10 点统一上传
2024-10-01 20:38:29,379 - root - INFO - 识别到URL: []
2024-10-01 20:55:28,686 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720717.html#第7讲 物质的量浓度-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 20:55:28,687 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720717.html']
2024-10-01 20:55:28,687 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720717.html
2024-10-01 20:55:28,843 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720716.html#第6讲 物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 20:55:28,844 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720716.html']
2024-10-01 20:55:28,844 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720716.html
2024-10-01 20:55:29,016 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720715.html#第5讲 氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 20:55:29,018 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720715.html']
2024-10-01 20:55:29,022 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720715.html
2024-10-01 20:55:29,175 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720714.html#第4讲 氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 20:55:29,175 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720714.html']
2024-10-01 20:55:29,175 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720714.html
2024-10-01 20:55:43,468 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第4讲+氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:55:43,852 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第6讲+物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:55:44,370 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: @A圆圆老师-教务处 用普通账号发
2024-10-01 20:55:44,371 - root - INFO - 识别到URL: []
2024-10-01 20:55:47,686 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第5讲+氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:55:48,769 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: 要不识别不了
2024-10-01 20:55:48,770 - root - INFO - 识别到URL: []
2024-10-01 20:55:48,896 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第6讲+物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:55:49,506 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第4讲+氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:55:52,718 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第5讲+氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:55:53,902 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第6讲+物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx, 准备上传
2024-10-01 20:55:53,903 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第6讲+物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:55:54,513 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第4讲+氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx, 准备上传
2024-10-01 20:55:54,513 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第4讲+氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:55:56,496 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:55:57,549 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:55:57,727 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第5讲+氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx, 准备上传
2024-10-01 20:55:57,728 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第5讲+氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:56:00,102 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:57:09,980 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720715.html#第5讲 氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 20:57:09,982 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720715.html']
2024-10-01 20:57:09,982 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720715.html
2024-10-01 20:57:10,122 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720716.html#第6讲 物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 20:57:10,122 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720716.html']
2024-10-01 20:57:10,122 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720716.html
2024-10-01 20:57:10,295 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720714.html#第4讲 氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 20:57:10,301 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720714.html']
2024-10-01 20:57:10,301 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720714.html
2024-10-01 20:57:10,462 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720717.html#第7讲 物质的量浓度-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 20:57:10,463 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720717.html']
2024-10-01 20:57:10,463 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720717.html
2024-10-01 20:57:19,988 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第5讲+氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:57:20,387 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第4讲+氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:57:21,533 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第6讲+物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:57:25,408 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第4讲+氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:57:25,507 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第7讲+物质的量浓度-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:57:26,012 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第5讲+氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:57:27,546 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第6讲+物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:57:30,412 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第4讲+氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx, 准备上传
2024-10-01 20:57:30,413 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第4讲+氧化还原反应的概念和规律-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:57:31,018 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第5讲+氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx, 准备上传
2024-10-01 20:57:31,018 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第5讲+氧化还原反应方程式的书写与配平-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:57:31,528 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第7讲+物质的量浓度-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 20:57:32,551 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第6讲+物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx, 准备上传
2024-10-01 20:57:32,552 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第6讲+物质的量　气体摩尔体积-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:57:33,110 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:57:33,603 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:57:34,727 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:57:36,534 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第7讲+物质的量浓度-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx, 准备上传
2024-10-01 20:57:36,534 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第7讲+物质的量浓度-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 20:57:38,926 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:16:41,901 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/44216419.html#2024年中考化学实验基本技能----气体的收集
2024-10-01 21:16:41,903 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/44216419.html']
2024-10-01 21:16:41,903 - root - INFO - 打开URL: https://m.zxxk.com/soft/44216419.html
2024-10-01 21:17:24,652 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/2024年中考化学实验基本技能----气体的收集.zip
2024-10-01 21:17:30,673 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/2024年中考化学实验基本技能----气体的收集.zip
2024-10-01 21:17:35,678 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/2024年中考化学实验基本技能----气体的收集.zip, 准备上传
2024-10-01 21:17:35,679 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/2024年中考化学实验基本技能----气体的收集.zip 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:17:37,306 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:23:50,961 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47611613.html
2024-10-01 21:23:50,963 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47611613.html']
2024-10-01 21:23:50,963 - root - INFO - 打开URL: https://www.zxxk.com/soft/47611613.html
2024-10-01 21:24:28,890 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第2章+声音与环境-【速记清单】-【新教材】2024-2025学年八年级物理上册单元速记·巧练（沪粤版2024）.zip
2024-10-01 21:24:34,914 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第2章+声音与环境-【速记清单】-【新教材】2024-2025学年八年级物理上册单元速记·巧练（沪粤版2024）.zip
2024-10-01 21:24:39,920 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第2章+声音与环境-【速记清单】-【新教材】2024-2025学年八年级物理上册单元速记·巧练（沪粤版2024）.zip, 准备上传
2024-10-01 21:24:39,920 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第2章+声音与环境-【速记清单】-【新教材】2024-2025学年八年级物理上册单元速记·巧练（沪粤版2024）.zip 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:24:43,109 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:36:34,457 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/39720718.html#第8讲 化学计算的常用方法-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）
2024-10-01 21:36:34,459 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/39720718.html']
2024-10-01 21:36:34,459 - root - INFO - 打开URL: https://m.zxxk.com/soft/39720718.html
2024-10-01 21:37:14,099 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第8讲+化学计算的常用方法-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 21:37:20,116 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第8讲+化学计算的常用方法-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx
2024-10-01 21:37:25,118 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第8讲+化学计算的常用方法-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx, 准备上传
2024-10-01 21:37:25,118 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第8讲+化学计算的常用方法-【精梳精讲】2024年高考化学大一轮精品复习课件（新教材）.pptx 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:37:27,905 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:45:07,844 - itchat - ERROR - Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=jGfR67817KKiJ5Pj&skey=@crypt_97de4bb_10cdbb594df6fcf1dba42e040e82290e&pass_ticket=7BU5cB8HJcM5E3DLPQngj6wr7m0a2OTGnG%2BgErxfoQs28wTzM7Yh8AbqSSRbDWTUFs%2F6t%2FDsUYauGOnWfWnAhQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 301, in maintain_loop
    msgList, contactList = self.get_msg()
                           ^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 390, in get_msg
    r = self.s.post(url, data=json.dumps(data),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=jGfR67817KKiJ5Pj&skey=@crypt_97de4bb_10cdbb594df6fcf1dba42e040e82290e&pass_ticket=7BU5cB8HJcM5E3DLPQngj6wr7m0a2OTGnG%2BgErxfoQs28wTzM7Yh8AbqSSRbDWTUFs%2F6t%2FDsUYauGOnWfWnAhQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

2024-10-01 21:52:45,656 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47677827.html
2024-10-01 21:52:45,659 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47677827.html']
2024-10-01 21:52:45,660 - root - INFO - 打开URL: https://www.zxxk.com/soft/47677827.html
2024-10-01 21:53:02,975 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/专题2.1+不等式的性质及其应用-2024-2025学年上学期高一数学核心考点突破（人教版2019）.zip
2024-10-01 21:53:09,006 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/专题2.1+不等式的性质及其应用-2024-2025学年上学期高一数学核心考点突破（人教版2019）.zip
2024-10-01 21:53:13,282 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47677873.html
2024-10-01 21:53:13,283 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47677873.html']
2024-10-01 21:53:13,283 - root - INFO - 打开URL: https://www.zxxk.com/soft/47677873.html
2024-10-01 21:53:14,012 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/专题2.1+不等式的性质及其应用-2024-2025学年上学期高一数学核心考点突破（人教版2019）.zip, 准备上传
2024-10-01 21:53:14,012 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/专题2.1+不等式的性质及其应用-2024-2025学年上学期高一数学核心考点突破（人教版2019）.zip 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:53:15,410 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:53:23,259 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/专题2.3+一元二次不等式及其应用-2024—2025学年上学期高一数学核心考点突破（人教A版2019）.zip
2024-10-01 21:53:28,501 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47174020.html
2024-10-01 21:53:28,503 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47174020.html']
2024-10-01 21:53:28,503 - root - INFO - 打开URL: https://www.zxxk.com/soft/47174020.html
2024-10-01 21:53:30,290 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/专题2.3+一元二次不等式及其应用-2024—2025学年上学期高一数学核心考点突破（人教A版2019）.zip
2024-10-01 21:53:35,294 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/专题2.3+一元二次不等式及其应用-2024—2025学年上学期高一数学核心考点突破（人教A版2019）.zip, 准备上传
2024-10-01 21:53:35,295 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/专题2.3+一元二次不等式及其应用-2024—2025学年上学期高一数学核心考点突破（人教A版2019）.zip 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:53:37,311 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:53:44,775 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/拓展2-2+解含参二次不等式及恒成立有解问题（五大题型）-2024-2025学年高一数学重难点突破及易错点分析（人教A版2019必修第一册）.zip
2024-10-01 21:53:50,796 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/拓展2-2+解含参二次不等式及恒成立有解问题（五大题型）-2024-2025学年高一数学重难点突破及易错点分析（人教A版2019必修第一册）.zip
2024-10-01 21:53:55,801 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/拓展2-2+解含参二次不等式及恒成立有解问题（五大题型）-2024-2025学年高一数学重难点突破及易错点分析（人教A版2019必修第一册）.zip, 准备上传
2024-10-01 21:53:55,801 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/拓展2-2+解含参二次不等式及恒成立有解问题（五大题型）-2024-2025学年高一数学重难点突破及易错点分析（人教A版2019必修第一册）.zip 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:53:57,307 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:54:11,887 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/拓展2-2+解含参二次不等式及恒成立有解问题（五大题型）-2024-2025学年高一数学重难点突破及易错点分析（人教A版2019必修第一册）.zip
2024-10-01 21:54:17,907 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/拓展2-2+解含参二次不等式及恒成立有解问题（五大题型）-2024-2025学年高一数学重难点突破及易错点分析（人教A版2019必修第一册）.zip
2024-10-01 21:54:22,913 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/拓展2-2+解含参二次不等式及恒成立有解问题（五大题型）-2024-2025学年高一数学重难点突破及易错点分析（人教A版2019必修第一册）.zip, 准备上传
2024-10-01 21:54:22,913 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/拓展2-2+解含参二次不等式及恒成立有解问题（五大题型）-2024-2025学年高一数学重难点突破及易错点分析（人教A版2019必修第一册）.zip 至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 21:54:24,389 - root - INFO - 文件已上传至群组: @@2e191464f166c0f281f96ad18bef990d0c6178c52fd046a6982693c0a96ab46f
2024-10-01 22:03:24,508 - root - INFO - 接收到退出信号，正在停止程序...
2024-10-01 22:03:24,508 - root - INFO - 停止监控下载目录
2024-10-01 22:06:03,817 - root - INFO - 日志系统初始化成功
2024-10-01 22:06:03,818 - root - INFO - 应用启动
2024-10-01 22:06:03,818 - root - INFO - 配置文件加载成功
2024-10-01 22:06:03,818 - root - INFO - 配置文件加载成功
2024-10-01 22:06:04,373 - itchat - ERROR - Hot reload failed, logging in normally, error={'BaseResponse': {'ErrMsg': '服务器拒绝连接', 'Ret': -1003, 'RawMsg': 'server refused, loading login status failed.'}}
2024-10-01 22:06:04,373 - itchat - INFO - Ready to login.
2024-10-01 22:06:04,373 - itchat - INFO - Getting uuid of QR code.
2024-10-01 22:06:04,638 - itchat - INFO - Downloading QR code.
2024-10-01 22:06:43,050 - root - INFO - 日志系统初始化成功
2024-10-01 22:06:43,050 - root - INFO - 应用启动
2024-10-01 22:06:43,050 - root - INFO - 配置文件加载成功
2024-10-01 22:06:43,050 - root - INFO - 配置文件加载成功
2024-10-01 22:06:43,541 - itchat - ERROR - Hot reload failed, logging in normally, error={'BaseResponse': {'ErrMsg': '服务器拒绝连接', 'Ret': -1003, 'RawMsg': 'server refused, loading login status failed.'}}
2024-10-01 22:06:43,541 - itchat - INFO - Ready to login.
2024-10-01 22:06:43,541 - itchat - INFO - Getting uuid of QR code.
2024-10-01 22:06:43,751 - itchat - INFO - Downloading QR code.
2024-10-01 22:08:49,507 - root - INFO - 日志系统初始化成功
2024-10-01 22:08:49,507 - root - INFO - 应用启动
2024-10-01 22:08:49,508 - root - INFO - 配置文件加载成功
2024-10-01 22:08:49,508 - root - INFO - 配置文件加载成功
2024-10-01 22:08:49,952 - itchat - ERROR - Hot reload failed, logging in normally, error={'BaseResponse': {'ErrMsg': '服务器拒绝连接', 'Ret': -1003, 'RawMsg': 'server refused, loading login status failed.'}}
2024-10-01 22:08:49,952 - itchat - INFO - Ready to login.
2024-10-01 22:08:49,952 - itchat - INFO - Getting uuid of QR code.
2024-10-01 22:08:50,163 - itchat - INFO - Downloading QR code.
2024-10-01 22:12:32,671 - root - INFO - 日志系统初始化成功
2024-10-01 22:12:32,672 - root - INFO - 应用启动
2024-10-01 22:12:32,672 - root - INFO - 配置文件加载成功
2024-10-01 22:12:32,672 - root - INFO - 配置文件加载成功
2024-10-01 22:12:33,122 - itchat - ERROR - Hot reload failed, logging in normally, error={'BaseResponse': {'ErrMsg': '服务器拒绝连接', 'Ret': -1003, 'RawMsg': 'server refused, loading login status failed.'}}
2024-10-01 22:12:33,122 - itchat - INFO - Ready to login.
2024-10-01 22:12:33,122 - itchat - INFO - Getting uuid of QR code.
2024-10-01 22:12:33,347 - itchat - INFO - Downloading QR code.
2024-10-01 22:15:28,514 - root - ERROR - 异常捕获: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/login?loginicon=true&uuid=gfCf5RghAA==&tip=1&r=-1094231&_=1727792104 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/login?loginicon=true&uuid=gfCf5RghAA==&tip=1&r=-1094231&_=1727792104 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 19, in login
    try:
        ^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 34, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 150, in check_login
    r = self.s.get(url, params=params, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/login?loginicon=true&uuid=gfCf5RghAA==&tip=1&r=-1094231&_=1727792104 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-01 22:15:28,521 - root - ERROR - 未登录微信，无法发送通知
2024-10-01 22:15:28,521 - root - CRITICAL - 应用启动失败: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/login?loginicon=true&uuid=gfCf5RghAA==&tip=1&r=-1094231&_=1727792104 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/login?loginicon=true&uuid=gfCf5RghAA==&tip=1&r=-1094231&_=1727792104 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/app.py", line 37, in main
    itchat_handler.login()
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 23, in login
    qrCallback=self.save_qr
    ^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 19, in login
    try:
        ^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 34, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 150, in check_login
    r = self.s.get(url, params=params, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/login?loginicon=true&uuid=gfCf5RghAA==&tip=1&r=-1094231&_=1727792104 (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-02 06:21:02,885 - root - INFO - 日志系统初始化成功
2024-10-02 06:21:02,886 - root - INFO - 应用启动
2024-10-02 06:21:02,886 - root - INFO - 配置文件加载成功
2024-10-02 06:21:02,886 - root - INFO - 配置文件加载成功
2024-10-02 06:21:03,485 - itchat - ERROR - Hot reload failed, logging in normally, error={'BaseResponse': {'ErrMsg': '服务器拒绝连接', 'Ret': -1003, 'RawMsg': 'server refused, loading login status failed.'}}
2024-10-02 06:21:03,485 - itchat - INFO - Ready to login.
2024-10-02 06:21:03,485 - itchat - INFO - Getting uuid of QR code.
2024-10-02 06:21:03,700 - itchat - INFO - Downloading QR code.
2024-10-02 06:21:03,747 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:21:29,048 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:21:54,338 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:25:33,241 - root - INFO - 日志系统初始化成功
2024-10-02 06:25:33,241 - root - INFO - 应用启动
2024-10-02 06:25:33,242 - root - INFO - 配置文件加载成功
2024-10-02 06:25:33,242 - root - INFO - 配置文件加载成功
2024-10-02 06:25:33,541 - itchat - ERROR - Hot reload failed, logging in normally, error={'BaseResponse': {'ErrMsg': '文件位置错误', 'Ret': -1002, 'RawMsg': 'No such file, loading login status failed.'}}
2024-10-02 06:25:33,541 - itchat - INFO - Ready to login.
2024-10-02 06:25:33,542 - itchat - INFO - Getting uuid of QR code.
2024-10-02 06:25:33,782 - itchat - INFO - Downloading QR code.
2024-10-02 06:25:33,821 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 21, in login
    itchat.auto_login(
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 34, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 56, in login
    qrStorage = self.get_QR(enableCmdQR=enableCmdQR,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 132, in get_QR
    qrCallback(uuid=uuid, status='0', qrcode=qrStorage.getvalue())
TypeError: ItChatHandler.save_qr() got an unexpected keyword argument 'qrcode'
2024-10-02 06:25:33,822 - root - CRITICAL - 应用启动失败: 'Notifier' object has no attribute 'notify'
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 21, in login
    itchat.auto_login(
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 34, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 56, in login
    qrStorage = self.get_QR(enableCmdQR=enableCmdQR,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/login.py", line 132, in get_QR
    qrCallback(uuid=uuid, status='0', qrcode=qrStorage.getvalue())
TypeError: ItChatHandler.save_qr() got an unexpected keyword argument 'qrcode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/app.py", line 37, in main
    itchat_handler.login()
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 28, in login
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 46, in handle_exception
    self.notifier.notify(f"系统异常: {exception}")
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 06:28:50,227 - root - INFO - 日志系统初始化成功
2024-10-02 06:28:50,227 - root - INFO - 应用启动
2024-10-02 06:28:50,227 - root - INFO - 配置文件加载成功
2024-10-02 06:28:50,227 - root - INFO - 配置文件加载成功
2024-10-02 06:28:50,540 - itchat - ERROR - Hot reload failed, logging in normally, error={'BaseResponse': {'ErrMsg': '文件位置错误', 'Ret': -1002, 'RawMsg': 'No such file, loading login status failed.'}}
2024-10-02 06:28:50,540 - itchat - INFO - Ready to login.
2024-10-02 06:28:50,540 - itchat - INFO - Getting uuid of QR code.
2024-10-02 06:28:50,750 - itchat - INFO - Downloading QR code.
2024-10-02 06:28:50,799 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:28:50,945 - root - INFO - 二维码图片已显示，请扫描登录微信。
2024-10-02 06:28:56,950 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:28:57,066 - root - INFO - 二维码图片已显示，请扫描登录微信。
2024-10-02 06:28:57,067 - itchat - INFO - Please press confirm on your phone.
2024-10-02 06:29:04,683 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:29:04,776 - root - INFO - 二维码图片已显示，请扫描登录微信。
2024-10-02 06:29:05,394 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:29:05,493 - root - INFO - 二维码图片已显示，请扫描登录微信。
2024-10-02 06:29:06,109 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:29:06,191 - root - INFO - 二维码图片已显示，请扫描登录微信。
2024-10-02 06:29:07,879 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:29:07,954 - root - INFO - 二维码图片已显示，请扫描登录微信。
2024-10-02 06:29:07,954 - itchat - INFO - Loading the contact, this may take a little while.
2024-10-02 06:29:12,482 - itchat - INFO - Login successfully as 李老师呀
2024-10-02 06:29:12,487 - root - INFO - 微信登录成功
2024-10-02 06:29:12,487 - root - INFO - 找到群组 '🐠【学虎】课件下载' 的 UserName: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:29:12,488 - itchat - INFO - Start auto replying.
2024-10-02 06:29:12,568 - root - INFO - 开始监控下载目录: /Users/martinezdavid/Downloads
2024-10-02 06:29:36,849 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/47701070.html#精品解析：2022年福建省中考模拟语文试题
2024-10-02 06:29:36,850 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/47701070.html']
2024-10-02 06:29:36,851 - root - INFO - 打开URL: https://m.zxxk.com/soft/47701070.html
2024-10-02 06:29:37,131 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/47696935.html#专题15 散文阅读-备战2025年中考语文专项精练（山东青岛专用）
2024-10-02 06:29:37,131 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/47696935.html']
2024-10-02 06:29:37,131 - root - INFO - 打开URL: https://m.zxxk.com/soft/47696935.html
2024-10-02 06:29:37,240 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/46823351.html# 小数除法（经典例题）（综合练习）-2024-2025学年五年级上册数学人教版
2024-10-02 06:29:37,240 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/46823351.html']
2024-10-02 06:29:37,240 - root - INFO - 打开URL: https://m.zxxk.com/soft/46823351.html
2024-10-02 06:29:38,346 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47608132.html
2024-10-02 06:29:38,346 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47608132.html']
2024-10-02 06:29:38,347 - root - INFO - 打开URL: https://www.zxxk.com/soft/47608132.html
2024-10-02 06:29:38,584 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47642171.html
2024-10-02 06:29:38,584 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47642171.html']
2024-10-02 06:29:38,584 - root - INFO - 打开URL: https://www.zxxk.com/soft/47642171.html
2024-10-02 06:29:38,735 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47608131.html
2024-10-02 06:29:38,735 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47608131.html']
2024-10-02 06:29:38,735 - root - INFO - 打开URL: https://www.zxxk.com/soft/47608131.html
2024-10-02 06:29:39,024 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47591799.html
2024-10-02 06:29:39,025 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47591799.html']
2024-10-02 06:29:39,025 - root - INFO - 打开URL: https://www.zxxk.com/soft/47591799.html
2024-10-02 06:29:39,825 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47608130.html
2024-10-02 06:29:39,825 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47608130.html']
2024-10-02 06:29:39,825 - root - INFO - 打开URL: https://www.zxxk.com/soft/47608130.html
2024-10-02 06:29:40,116 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47585257.html
2024-10-02 06:29:40,117 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47585257.html']
2024-10-02 06:29:40,117 - root - INFO - 打开URL: https://www.zxxk.com/soft/47585257.html
2024-10-02 06:29:40,330 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/47585256.html
2024-10-02 06:29:40,330 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/47585256.html']
2024-10-02 06:29:40,330 - root - INFO - 打开URL: https://www.zxxk.com/soft/47585256.html
2024-10-02 06:32:02,894 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/+小数除法（经典例题）（综合练习）-2024-2025学年五年级上册数学人教版.docx
2024-10-02 06:32:04,554 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/专题15+散文阅读-备战2025年中考语文专项精练（山东青岛专用）.zip
2024-10-02 06:32:07,517 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【C卷·思维拓展卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip
2024-10-02 06:32:08,909 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/+小数除法（经典例题）（综合练习）-2024-2025学年五年级上册数学人教版.docx
2024-10-02 06:32:11,579 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/专题15+散文阅读-备战2025年中考语文专项精练（山东青岛专用）.zip
2024-10-02 06:32:12,914 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/（计算能力）第三单元+分数除法-解方程-2024-2025学年六年级上册数学小马虎错题本（人教版）.zip
2024-10-02 06:32:13,538 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【C卷·思维拓展卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip
2024-10-02 06:32:13,913 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/+小数除法（经典例题）（综合练习）-2024-2025学年五年级上册数学人教版.docx, 准备上传
2024-10-02 06:32:13,914 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/+小数除法（经典例题）（综合练习）-2024-2025学年五年级上册数学人教版.docx 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:15,037 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:16,583 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/专题15+散文阅读-备战2025年中考语文专项精练（山东青岛专用）.zip, 准备上传
2024-10-02 06:32:16,583 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/专题15+散文阅读-备战2025年中考语文专项精练（山东青岛专用）.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:17,990 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【B卷·素养提高卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip
2024-10-02 06:32:18,521 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:18,541 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【C卷·思维拓展卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip, 准备上传
2024-10-02 06:32:18,541 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【C卷·思维拓展卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:18,940 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/（计算能力）第三单元+分数除法-解方程-2024-2025学年六年级上册数学小马虎错题本（人教版）.zip
2024-10-02 06:32:19,399 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:21,604 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【A卷·基础巩固卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip
2024-10-02 06:32:22,780 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/（总集篇）第三单元分数除法·总集篇·工程问题【二十大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip
2024-10-02 06:32:23,945 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/（计算能力）第三单元+分数除法-解方程-2024-2025学年六年级上册数学小马虎错题本（人教版）.zip, 准备上传
2024-10-02 06:32:23,945 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/（计算能力）第三单元+分数除法-解方程-2024-2025学年六年级上册数学小马虎错题本（人教版）.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:24,014 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【B卷·素养提高卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip
2024-10-02 06:32:24,884 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:27,796 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/（总集篇）第三单元分数除法·总集篇·工程问题【二十大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip
2024-10-02 06:32:28,624 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【A卷·基础巩固卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip
2024-10-02 06:32:29,019 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【B卷·素养提高卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip, 准备上传
2024-10-02 06:32:29,020 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【B卷·素养提高卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:30,255 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:32,802 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/（总集篇）第三单元分数除法·总集篇·工程问题【二十大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip, 准备上传
2024-10-02 06:32:32,802 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/（总集篇）第三单元分数除法·总集篇·工程问题【二十大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:33,629 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【A卷·基础巩固卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip, 准备上传
2024-10-02 06:32:33,629 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第三单元分数除法检测卷【A卷·基础巩固卷】-2024-2025学年六年级数学上册典型例题系列（A3+A4+解析卷）人教版.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:34,056 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/（篇一）第三单元分数除法·基础计算篇【十大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip
2024-10-02 06:32:34,753 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:35,152 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/精品解析：2022年福建省中考模拟语文试题.zip
2024-10-02 06:32:35,188 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:40,080 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/（篇一）第三单元分数除法·基础计算篇【十大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip
2024-10-02 06:32:41,167 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/精品解析：2022年福建省中考模拟语文试题.zip
2024-10-02 06:32:45,081 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/（篇一）第三单元分数除法·基础计算篇【十大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip, 准备上传
2024-10-02 06:32:45,082 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/（篇一）第三单元分数除法·基础计算篇【十大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:46,172 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/精品解析：2022年福建省中考模拟语文试题.zip, 准备上传
2024-10-02 06:32:46,172 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/精品解析：2022年福建省中考模拟语文试题.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:47,360 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:47,963 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:32:53,036 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/（篇二）第三单元分数除法·简便计算篇【十五大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip
2024-10-02 06:32:59,055 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/（篇二）第三单元分数除法·简便计算篇【十五大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip
2024-10-02 06:33:04,057 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/（篇二）第三单元分数除法·简便计算篇【十五大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip, 准备上传
2024-10-02 06:33:04,058 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/（篇二）第三单元分数除法·简便计算篇【十五大考点】-2024-2025学年六年级数学上册典型例题系列（原卷版+解析版）人教版.zip 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:33:06,529 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:34:32,682 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/47591795.html#10《牛郎织女（一）》同步检测-2024-2025学年语文五年级上册统编版
2024-10-02 06:34:32,683 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/47591795.html']
2024-10-02 06:34:32,683 - root - INFO - 打开URL: https://m.zxxk.com/soft/47591795.html
2024-10-02 06:34:32,862 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/40393217.html#第11课 牛郎织女（二）-2023-2024学年五年级语文上册同步分层作业设计系列（统编版）
2024-10-02 06:34:32,863 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/40393217.html']
2024-10-02 06:34:32,863 - root - INFO - 打开URL: https://m.zxxk.com/soft/40393217.html
2024-10-02 06:34:33,372 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/30305052.html#【培优导航·高效练习】五年级上册语文培优拔高一课一练-12 古诗三首（同步练习）-人教部编版（含答案）
2024-10-02 06:34:33,372 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/30305052.html']
2024-10-02 06:34:33,372 - root - INFO - 打开URL: https://m.zxxk.com/soft/30305052.html
2024-10-02 06:34:33,579 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/35506006.html#五年级语文上册13《少年中国说》同步练习（有答案）
2024-10-02 06:34:33,579 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/35506006.html']
2024-10-02 06:34:33,579 - root - INFO - 打开URL: https://m.zxxk.com/soft/35506006.html
2024-10-02 06:34:33,791 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/30305054.html#【培优导航·高效练习】五年级上册语文培优拔高一课一练-14 圆明园的毁灭（同步练习）-人教部编版（含答案）
2024-10-02 06:34:33,796 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/30305054.html']
2024-10-02 06:34:33,796 - root - INFO - 打开URL: https://m.zxxk.com/soft/30305054.html
2024-10-02 06:34:34,016 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/30305056.html#【培优导航·高效练习】五年级上册语文培优拔高一课一练-15 小岛（同步练习）-人教部编版（含答案）
2024-10-02 06:34:34,016 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/30305056.html']
2024-10-02 06:34:34,016 - root - INFO - 打开URL: https://m.zxxk.com/soft/30305056.html
2024-10-02 06:34:46,897 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/10《牛郎织女（一）》同步检测-2024-2025学年语文五年级上册统编版.docx
2024-10-02 06:34:49,353 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/五年级语文上册13《少年中国说》同步练习（有答案）.docx
2024-10-02 06:34:52,919 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/10《牛郎织女（一）》同步检测-2024-2025学年语文五年级上册统编版.docx
2024-10-02 06:34:55,382 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/五年级语文上册13《少年中国说》同步练习（有答案）.docx
2024-10-02 06:34:57,797 - root - INFO - 检测到移动后的新文件: /Users/martinezdavid/Downloads/第11课+牛郎织女（二）-2023-2024学年五年级语文上册同步分层作业设计系列（统编版）.docx
2024-10-02 06:34:57,924 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/10《牛郎织女（一）》同步检测-2024-2025学年语文五年级上册统编版.docx, 准备上传
2024-10-02 06:34:57,925 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/10《牛郎织女（一）》同步检测-2024-2025学年语文五年级上册统编版.docx 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:35:00,386 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/五年级语文上册13《少年中国说》同步练习（有答案）.docx, 准备上传
2024-10-02 06:35:00,387 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/五年级语文上册13《少年中国说》同步练习（有答案）.docx 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:35:01,467 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:35:03,814 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第11课+牛郎织女（二）-2023-2024学年五年级语文上册同步分层作业设计系列（统编版）.docx
2024-10-02 06:35:08,816 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第11课+牛郎织女（二）-2023-2024学年五年级语文上册同步分层作业设计系列（统编版）.docx, 准备上传
2024-10-02 06:35:08,816 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第11课+牛郎织女（二）-2023-2024学年五年级语文上册同步分层作业设计系列（统编版）.docx 至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:35:09,953 - root - INFO - 文件已上传至群组: @@71c5a33813d677c80f6b8f8206532f084b6508eccbf8de9d71e31f93053e3be2
2024-10-02 06:35:16,999 - root - ERROR - 上传失败: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/file_upload/uploader.py", line 79, in _upload_chunk
    itchat.send_file(file_path, toUserName=user_name)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 383, in send_file
    r = self.upload_file(fileDir, preparedFile=preparedFile)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 334, in upload_file
    r = upload_chunk_file(self, fileDir, fileSymbol, fileSize,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 367, in upload_chunk_file
    return core.s.post(url, files=files, headers=headers, timeout=config.TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-02 06:35:17,012 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/file_upload/uploader.py", line 79, in _upload_chunk
    itchat.send_file(file_path, toUserName=user_name)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 383, in send_file
    r = self.upload_file(fileDir, preparedFile=preparedFile)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 334, in upload_file
    r = upload_chunk_file(self, fileDir, fileSymbol, fileSize,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 367, in upload_chunk_file
    return core.s.post(url, files=files, headers=headers, timeout=config.TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2024-10-02 06:35:17,013 - root - ERROR - 上传文件时发生错误: 'Notifier' object has no attribute 'notify'
Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/file_upload/uploader.py", line 79, in _upload_chunk
    itchat.send_file(file_path, toUserName=user_name)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 383, in send_file
    r = self.upload_file(fileDir, preparedFile=preparedFile)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 334, in upload_file
    r = upload_chunk_file(self, fileDir, fileSymbol, fileSize,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 367, in upload_chunk_file
    return core.s.post(url, files=files, headers=headers, timeout=config.TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/file_upload/uploader.py", line 68, in _upload_file_thread
    self._upload_chunk(file_path, user_name)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/file_upload/uploader.py", line 84, in _upload_chunk
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 46, in handle_exception
    self.notifier.notify(f"系统异常: {exception}")
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 06:35:17,014 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 1419, in getresponse
    response.begin()
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/file_upload/uploader.py", line 79, in _upload_chunk
    itchat.send_file(file_path, toUserName=user_name)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 383, in send_file
    r = self.upload_file(fileDir, preparedFile=preparedFile)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 334, in upload_file
    r = upload_chunk_file(self, fileDir, fileSymbol, fileSize,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/messages.py", line 367, in upload_chunk_file
    return core.s.post(url, files=files, headers=headers, timeout=config.TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/file_upload/uploader.py", line 68, in _upload_file_thread
    self._upload_chunk(file_path, user_name)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/file_upload/uploader.py", line 84, in _upload_chunk
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 46, in handle_exception
    self.notifier.notify(f"系统异常: {exception}")
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 06:44:31,034 - root - INFO - 接收到退出信号，正在停止程序...
2024-10-02 06:44:31,036 - root - INFO - 停止监控下载目录
2024-10-02 06:44:31,319 - root - INFO - 日志系统初始化成功
2024-10-02 06:44:31,319 - root - INFO - 应用启动
2024-10-02 06:44:31,320 - root - INFO - 配置文件加载成功
2024-10-02 06:44:31,320 - root - INFO - 配置文件加载成功
2024-10-02 06:44:31,320 - root - INFO - 已删除旧的会话文件: itchat.pkl
2024-10-02 06:44:31,529 - itchat - INFO - Ready to login.
2024-10-02 06:44:31,530 - itchat - INFO - Getting uuid of QR code.
2024-10-02 06:44:31,744 - itchat - INFO - Downloading QR code.
2024-10-02 06:44:31,821 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:44:56,997 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:45:22,163 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:45:47,308 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:46:12,457 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:46:37,622 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:47:02,783 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:47:27,955 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:47:53,117 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:48:18,265 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:48:43,400 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:49:08,518 - root - INFO - 二维码已保存到 qr.png
2024-10-02 06:49:25,968 - root - INFO - 日志系统初始化成功
2024-10-02 06:49:25,968 - root - INFO - 应用启动
2024-10-02 06:49:25,968 - root - INFO - 配置文件加载成功
2024-10-02 06:49:25,968 - root - INFO - 配置文件加载成功
2024-10-02 06:49:26,249 - itchat - INFO - Ready to login.
2024-10-02 06:49:26,250 - itchat - INFO - Getting uuid of QR code.
2024-10-02 06:49:26,456 - itchat - INFO - Downloading QR code.
2024-10-02 06:49:26,479 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:01:28,506 - root - INFO - 日志系统初始化成功
2024-10-02 08:01:28,507 - root - INFO - 应用启动
2024-10-02 08:01:28,507 - root - INFO - 配置文件加载成功
2024-10-02 08:01:28,507 - root - INFO - 配置文件加载成功
2024-10-02 08:01:28,742 - itchat - INFO - Ready to login.
2024-10-02 08:01:28,743 - itchat - INFO - Getting uuid of QR code.
2024-10-02 08:01:28,988 - itchat - INFO - Downloading QR code.
2024-10-02 08:01:29,030 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:01:49,894 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:01:49,894 - itchat - INFO - Please press confirm on your phone.
2024-10-02 08:01:57,528 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:01:58,162 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:01:58,797 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:02:00,272 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:02:00,272 - itchat - INFO - Loading the contact, this may take a little while.
2024-10-02 08:02:04,292 - itchat - INFO - Login successfully as 李老师呀
2024-10-02 08:02:04,293 - root - INFO - 微信登录成功
2024-10-02 08:02:04,294 - root - INFO - 找到群组 '🐠【学虎】课件下载' 的 UserName: @@e36bd6751d2f26995c306d5b1af0c7dba226a88faab0ee8ac5ccc6d0e096764f
2024-10-02 08:02:04,294 - itchat - INFO - Start auto replying.
2024-10-02 08:02:04,295 - root - INFO - 开始监控下载目录: /Users/martinezdavid/Downloads
2024-10-02 08:02:32,211 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/30305054.html#【培优导航·高效练习】五年级上册语文培优拔高一课一练-14 圆明园的毁灭（同步练习）-人教部编版（含答案）
2024-10-02 08:02:32,212 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/30305054.html']
2024-10-02 08:02:32,212 - root - INFO - 打开URL: https://m.zxxk.com/soft/30305054.html
2024-10-02 08:02:32,388 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:32,388 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:32,390 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:32,390 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:32,391 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:32,391 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:32,394 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:02:32,483 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/30305056.html#【培优导航·高效练习】五年级上册语文培优拔高一课一练-15 小岛（同步练习）-人教部编版（含答案）
2024-10-02 08:02:32,484 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/30305056.html']
2024-10-02 08:02:32,484 - root - INFO - 打开URL: https://m.zxxk.com/soft/30305056.html
2024-10-02 08:02:33,076 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:33,076 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:33,077 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,077 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,078 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,078 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,085 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:02:33,086 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/47041567.html
https://m.zxxk.com/soft/47041398.html
2024-10-02 08:02:33,086 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/47041567.html', 'https://m.zxxk.com/soft/47041398.html']
2024-10-02 08:02:33,088 - root - INFO - 打开URL: https://m.zxxk.com/soft/47041567.html
2024-10-02 08:02:33,238 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:33,238 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:33,239 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,239 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,240 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,240 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,243 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:02:33,243 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://zhijiao.xkw.com/doc/47415534.html
2024-10-02 08:02:33,243 - root - INFO - 识别到URL: ['https://zhijiao.xkw.com/doc/47415534.html']
2024-10-02 08:02:33,243 - root - INFO - 打开URL: https://zhijiao.xkw.com/doc/47415534.html
2024-10-02 08:02:33,449 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:33,450 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:33,451 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,451 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,456 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,456 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,463 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:02:33,464 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/46576568.html#小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）
2024-10-02 08:02:33,464 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/46576568.html']
2024-10-02 08:02:33,465 - root - INFO - 打开URL: https://m.zxxk.com/soft/46576568.html
2024-10-02 08:02:33,642 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:33,642 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:02:33,645 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,645 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,647 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,647 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:02:33,651 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:02:49,528 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）.docx
2024-10-02 08:02:54,550 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）.docx
2024-10-02 08:02:59,556 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）.docx, 准备上传
2024-10-02 08:02:59,557 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）.docx 至群组: @@e36bd6751d2f26995c306d5b1af0c7dba226a88faab0ee8ac5ccc6d0e096764f
2024-10-02 08:03:01,075 - root - INFO - 文件已上传至群组: @@e36bd6751d2f26995c306d5b1af0c7dba226a88faab0ee8ac5ccc6d0e096764f
2024-10-02 08:03:27,726 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）.pptx
2024-10-02 08:03:32,745 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）.pptx
2024-10-02 08:03:37,747 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）.pptx, 准备上传
2024-10-02 08:03:37,747 - root - WARNING - 文件大小 75129946 字节 超过企业微信限制的 52428800 字节。
2024-10-02 08:03:37,747 - root - ERROR - 未配置云上传器，无法分享文件链接。
2024-10-02 08:04:42,093 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）_副本.docx
2024-10-02 08:04:42,094 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）_副本.pptx
2024-10-02 08:04:47,107 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）_副本.docx
2024-10-02 08:04:47,115 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）_副本.pptx
2024-10-02 08:04:52,111 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）_副本.docx, 准备上传
2024-10-02 08:04:52,112 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/小数除法知识点总结及高频易错点精编卷（试题）小学数学五年级上册（人教版）_副本.docx 至群组: @@e36bd6751d2f26995c306d5b1af0c7dba226a88faab0ee8ac5ccc6d0e096764f
2024-10-02 08:04:52,118 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）_副本.pptx, 准备上传
2024-10-02 08:04:52,118 - root - WARNING - 文件大小 75129946 字节 超过企业微信限制的 52428800 字节。
2024-10-02 08:04:52,118 - root - ERROR - 未配置云上传器，无法分享文件链接。
2024-10-02 08:04:53,553 - root - INFO - 文件已上传至群组: @@e36bd6751d2f26995c306d5b1af0c7dba226a88faab0ee8ac5ccc6d0e096764f
2024-10-02 08:05:17,879 - root - INFO - 接收到退出信号，正在停止程序...
2024-10-02 08:05:17,880 - root - INFO - 停止监控下载目录
2024-10-02 08:06:46,254 - root - INFO - 日志系统初始化成功
2024-10-02 08:06:46,255 - root - INFO - 应用启动
2024-10-02 08:06:46,255 - root - INFO - 配置文件加载成功
2024-10-02 08:06:46,255 - root - INFO - 配置文件加载成功
2024-10-02 08:06:46,470 - itchat - INFO - Ready to login.
2024-10-02 08:06:46,470 - itchat - INFO - Getting uuid of QR code.
2024-10-02 08:06:46,674 - itchat - INFO - Downloading QR code.
2024-10-02 08:06:46,720 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:07:53,987 - root - INFO - 日志系统初始化成功
2024-10-02 08:07:53,988 - root - INFO - 应用启动
2024-10-02 08:07:53,988 - root - INFO - 配置文件加载成功
2024-10-02 08:07:53,988 - root - INFO - 配置文件加载成功
2024-10-02 08:07:54,266 - itchat - INFO - Ready to login.
2024-10-02 08:07:54,266 - itchat - INFO - Getting uuid of QR code.
2024-10-02 08:07:54,505 - itchat - INFO - Downloading QR code.
2024-10-02 08:07:54,544 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:08:01,476 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:08:01,477 - itchat - INFO - Please press confirm on your phone.
2024-10-02 08:08:09,102 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:08:09,719 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:08:10,334 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:08:11,809 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:08:11,809 - itchat - INFO - Loading the contact, this may take a little while.
2024-10-02 08:08:16,072 - itchat - INFO - Login successfully as 李老师呀
2024-10-02 08:08:16,073 - root - INFO - 微信登录成功
2024-10-02 08:08:16,073 - root - INFO - 找到群组 '🐠【学虎】课件下载' 的 UserName: @@3771501896e723420bf885f847a9e76d24ecd887d68e84db513ce581c157521a
2024-10-02 08:08:16,073 - itchat - INFO - Start auto replying.
2024-10-02 08:08:16,074 - root - INFO - 开始监控下载目录: /Users/martinezdavid/Downloads
2024-10-02 08:08:39,181 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）_副本.pptx
2024-10-02 08:08:44,199 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）_副本.pptx
2024-10-02 08:08:49,203 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第二章+机械运动（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）_副本.pptx, 准备上传
2024-10-02 08:08:49,204 - root - WARNING - 文件大小 75129946 字节 超过企业微信限制的 52428800 字节。
2024-10-02 08:08:49,204 - root - ERROR - 未配置云上传器，无法分享文件链接。
2024-10-02 08:11:16,719 - root - INFO - 接收到退出信号，正在停止程序...
2024-10-02 08:11:16,720 - root - INFO - 停止监控下载目录
2024-10-02 08:11:17,026 - root - INFO - 日志系统初始化成功
2024-10-02 08:11:17,026 - root - INFO - 应用启动
2024-10-02 08:11:17,026 - root - ERROR - 加载配置文件失败: Expecting value: line 13 column 13 (char 306)
2024-10-02 08:11:17,026 - root - CRITICAL - 应用启动失败: Expecting value: line 13 column 13 (char 306)
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/app.py", line 25, in main
    config = ConfigManager.load_config('src/config.json')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/config/config_manager.py", line 11, in load_config
    config = json.load(f)
             ^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 13 column 13 (char 306)
2024-10-02 08:11:20,303 - root - INFO - 日志系统初始化成功
2024-10-02 08:11:20,303 - root - INFO - 应用启动
2024-10-02 08:11:20,303 - root - ERROR - 加载配置文件失败: Expecting value: line 13 column 13 (char 306)
2024-10-02 08:11:20,303 - root - CRITICAL - 应用启动失败: Expecting value: line 13 column 13 (char 306)
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/app.py", line 25, in main
    config = ConfigManager.load_config('src/config.json')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/config/config_manager.py", line 11, in load_config
    config = json.load(f)
             ^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 13 column 13 (char 306)
2024-10-02 08:11:39,407 - root - INFO - 日志系统初始化成功
2024-10-02 08:11:39,407 - root - INFO - 应用启动
2024-10-02 08:11:39,407 - root - ERROR - 加载配置文件失败: Expecting value: line 13 column 13 (char 306)
2024-10-02 08:11:39,407 - root - CRITICAL - 应用启动失败: Expecting value: line 13 column 13 (char 306)
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/app.py", line 25, in main
    config = ConfigManager.load_config('src/config.json')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/config/config_manager.py", line 11, in load_config
    config = json.load(f)
             ^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 13 column 13 (char 306)
2024-10-02 08:12:05,542 - root - INFO - 日志系统初始化成功
2024-10-02 08:12:05,542 - root - INFO - 应用启动
2024-10-02 08:12:05,542 - root - ERROR - 加载配置文件失败: Expecting value: line 13 column 13 (char 306)
2024-10-02 08:12:05,542 - root - CRITICAL - 应用启动失败: Expecting value: line 13 column 13 (char 306)
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/app.py", line 25, in main
    config = ConfigManager.load_config('src/config.json')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/config/config_manager.py", line 11, in load_config
    config = json.load(f)
             ^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinezdavid/miniconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 13 column 13 (char 306)
2024-10-02 08:13:27,472 - root - INFO - 日志系统初始化成功
2024-10-02 08:13:27,474 - root - INFO - 应用启动
2024-10-02 08:13:27,474 - root - INFO - 配置文件加载成功
2024-10-02 08:13:27,474 - root - INFO - 配置文件加载成功
2024-10-02 08:13:27,739 - itchat - INFO - Ready to login.
2024-10-02 08:13:27,739 - itchat - INFO - Getting uuid of QR code.
2024-10-02 08:13:27,950 - itchat - INFO - Downloading QR code.
2024-10-02 08:13:27,987 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:13:53,142 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:14:18,286 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:14:43,462 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:14:44,920 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:14:44,920 - itchat - INFO - Please press confirm on your phone.
2024-10-02 08:14:52,559 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:14:53,189 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:14:53,789 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:14:55,227 - root - INFO - 二维码已保存到 qr.png
2024-10-02 08:14:55,227 - itchat - INFO - Loading the contact, this may take a little while.
2024-10-02 08:14:59,347 - itchat - INFO - Login successfully as 李老师呀
2024-10-02 08:14:59,348 - root - INFO - 微信登录成功
2024-10-02 08:14:59,349 - root - INFO - 找到群组 '🐠【学虎】课件下载' 的 UserName: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:14:59,349 - itchat - INFO - Start auto replying.
2024-10-02 08:14:59,352 - root - INFO - 开始监控下载目录: /Users/martinezdavid/Downloads
2024-10-02 08:23:12,617 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/38976276.html
2024-10-02 08:23:12,619 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/38976276.html']
2024-10-02 08:23:12,620 - root - INFO - 打开URL: https://www.zxxk.com/soft/38976276.html
2024-10-02 08:23:12,807 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:23:12,808 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:23:12,810 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:12,810 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:12,812 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:12,812 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:12,815 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:23:17,559 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/38976278.html
2024-10-02 08:23:17,560 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/38976278.html']
2024-10-02 08:23:17,560 - root - INFO - 打开URL: https://www.zxxk.com/soft/38976278.html
2024-10-02 08:23:17,697 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:23:17,697 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:23:17,698 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:17,698 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:17,699 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:17,699 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:17,701 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:23:22,698 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/38977622.html
2024-10-02 08:23:22,699 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/38977622.html']
2024-10-02 08:23:22,700 - root - INFO - 打开URL: https://www.zxxk.com/soft/38977622.html
2024-10-02 08:23:22,842 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:23:22,842 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:23:22,843 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:22,843 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:22,844 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:22,844 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:22,846 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:23:27,617 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://www.zxxk.com/soft/38977620.html
2024-10-02 08:23:27,618 - root - INFO - 识别到URL: ['https://www.zxxk.com/soft/38977620.html']
2024-10-02 08:23:27,618 - root - INFO - 打开URL: https://www.zxxk.com/soft/38977620.html
2024-10-02 08:23:27,744 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:23:27,744 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:23:27,745 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:27,745 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:27,746 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:27,746 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:23:27,749 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:23:31,210 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/第十三章+内能（单元知识清单）-【上好课】九年级物理全一册同步高效课堂（人教版）+.zip
2024-10-02 08:23:33,238 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/第十三章+内能（单元测试）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip
2024-10-02 08:23:36,247 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第十三章+内能（单元知识清单）-【上好课】九年级物理全一册同步高效课堂（人教版）+.zip
2024-10-02 08:23:38,269 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第十三章+内能（单元测试）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip
2024-10-02 08:23:38,277 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/第十四章+内能的利用（单元知识清单）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip
2024-10-02 08:23:41,258 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第十三章+内能（单元知识清单）-【上好课】九年级物理全一册同步高效课堂（人教版）+.zip, 准备上传
2024-10-02 08:23:41,259 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第十三章+内能（单元知识清单）-【上好课】九年级物理全一册同步高效课堂（人教版）+.zip 至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:23:43,275 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第十三章+内能（单元测试）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip, 准备上传
2024-10-02 08:23:43,275 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第十三章+内能（单元测试）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip 至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:23:43,310 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第十四章+内能的利用（单元知识清单）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip
2024-10-02 08:23:43,956 - root - INFO - 文件已上传至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:23:45,840 - root - INFO - 文件已上传至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:23:48,321 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第十四章+内能的利用（单元知识清单）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip, 准备上传
2024-10-02 08:23:48,321 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第十四章+内能的利用（单元知识清单）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip 至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:23:49,119 - root - INFO - 文件已上传至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:23:49,375 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/第十四章+内能的利用（单元测试）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip
2024-10-02 08:23:54,408 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第十四章+内能的利用（单元测试）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip
2024-10-02 08:23:59,416 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第十四章+内能的利用（单元测试）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip, 准备上传
2024-10-02 08:23:59,417 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/第十四章+内能的利用（单元测试）-【上好课】九年级物理全一册同步高效课堂（人教版）.zip 至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:24:08,594 - root - INFO - 文件已上传至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:37:23,210 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/45763631.html
2024-10-02 08:37:23,212 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/45763631.html']
2024-10-02 08:37:23,212 - root - INFO - 打开URL: https://m.zxxk.com/soft/45763631.html
2024-10-02 08:37:23,380 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:37:23,380 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:37:23,381 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:37:23,381 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:37:23,382 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:37:23,382 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:37:23,384 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:37:40,050 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/专题05++能量、速率与平衡-【好题汇编】2024年高考化学三模试题分类汇编（浙江专用）.zip
2024-10-02 08:37:45,066 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/专题05++能量、速率与平衡-【好题汇编】2024年高考化学三模试题分类汇编（浙江专用）.zip
2024-10-02 08:37:50,070 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/专题05++能量、速率与平衡-【好题汇编】2024年高考化学三模试题分类汇编（浙江专用）.zip, 准备上传
2024-10-02 08:37:50,070 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/专题05++能量、速率与平衡-【好题汇编】2024年高考化学三模试题分类汇编（浙江专用）.zip 至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:37:53,238 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/45763637.html
2024-10-02 08:37:53,239 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/45763637.html']
2024-10-02 08:37:53,239 - root - INFO - 打开URL: https://m.zxxk.com/soft/45763637.html
2024-10-02 08:37:53,406 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:37:53,406 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:37:53,407 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:37:53,407 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:37:53,408 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:37:53,408 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:37:53,410 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:37:54,060 - root - INFO - 文件已上传至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:38:07,198 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/专题10++化学反应原理综合题-【好题汇编】2024年高考化学三模试题分类汇编（浙江专用）.zip
2024-10-02 08:38:12,220 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/专题10++化学反应原理综合题-【好题汇编】2024年高考化学三模试题分类汇编（浙江专用）.zip
2024-10-02 08:38:17,224 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/专题10++化学反应原理综合题-【好题汇编】2024年高考化学三模试题分类汇编（浙江专用）.zip, 准备上传
2024-10-02 08:38:17,226 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/专题10++化学反应原理综合题-【好题汇编】2024年高考化学三模试题分类汇编（浙江专用）.zip 至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:38:21,613 - root - INFO - 文件已上传至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:42:22,565 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/47390817.html
https://m.zxxk.com/soft/46800924.html
2024-10-02 08:42:22,566 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/47390817.html', 'https://m.zxxk.com/soft/46800924.html']
2024-10-02 08:42:22,566 - root - INFO - 打开URL: https://m.zxxk.com/soft/47390817.html
2024-10-02 08:42:22,708 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:42:22,709 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:42:22,710 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:42:22,710 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:42:22,711 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:42:22,711 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:42:22,714 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:42:38,556 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/Unit+3+Pets+知识梳理-【上好课】2024-2025学年九年级英语上册同步精品课堂（牛津上海版）.zip
2024-10-02 08:42:43,577 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/Unit+3+Pets+知识梳理-【上好课】2024-2025学年九年级英语上册同步精品课堂（牛津上海版）.zip
2024-10-02 08:42:48,583 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/Unit+3+Pets+知识梳理-【上好课】2024-2025学年九年级英语上册同步精品课堂（牛津上海版）.zip, 准备上传
2024-10-02 08:42:48,584 - root - INFO - 正在上传文件: /Users/martinezdavid/Downloads/Unit+3+Pets+知识梳理-【上好课】2024-2025学年九年级英语上册同步精品课堂（牛津上海版）.zip 至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:42:49,995 - root - INFO - 文件已上传至群组: @@cfc2e907efff7be1539a59d710b4430b9bfd418a585a93f905ef225d66e4ccfd
2024-10-02 08:44:56,829 - root - INFO - 来自群组 🐠【学虎】课件下载 的消息: https://m.zxxk.com/soft/47142504.html
2024-10-02 08:44:56,831 - root - INFO - 识别到URL: ['https://m.zxxk.com/soft/47142504.html']
2024-10-02 08:44:56,831 - root - INFO - 打开URL: https://m.zxxk.com/soft/47142504.html
2024-10-02 08:44:56,986 - root - ERROR - 打开URL时发生错误: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:44:56,986 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'
2024-10-02 08:44:56,987 - root - ERROR - 处理消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:44:56,987 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:44:56,988 - root - ERROR - 处理群组消息时发生错误: 'Notifier' object has no attribute 'notify'
2024-10-02 08:44:56,988 - root - ERROR - 异常信息:
Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'
2024-10-02 08:44:56,991 - itchat - WARNING - Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 36, in open_url
    self.download_watcher.monitor_download(url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DownloadWatcher' object has no attribute 'monitor_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 34, in handle_message
    self.auto_clicker.open_url(clean_url)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/auto_click/auto_clicker.py", line 40, in open_url
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 71, in handle_group_messages
    self.message_callback(msg)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/message_handler.py", line 37, in handle_message
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/itchat_module/itchat_handler.py", line 76, in handle_group_messages
    self.error_handler.handle_exception(e)
  File "/Users/martinezdavid/Documents/MG/code/wechat-automation-project/src/error_handling/error_handler.py", line 59, in handle_exception
    self.notifier.notify(error_message)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notifier' object has no attribute 'notify'

2024-10-02 08:45:40,449 - root - INFO - 检测到新文件: /Users/martinezdavid/Downloads/第三章+声现象（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）.pptx
2024-10-02 08:45:45,470 - root - INFO - 文件下载完成且稳定: /Users/martinezdavid/Downloads/第三章+声现象（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）.pptx
2024-10-02 08:45:50,475 - root - INFO - 文件已稳定: /Users/martinezdavid/Downloads/第三章+声现象（单元复习课件）-【上好课】八年级物理上册同步高效课堂（沪科版·五四学制·2024）.pptx, 准备上传
2024-10-02 08:45:50,475 - root - WARNING - 文件大小 63531058 字节 超过企业微信限制的 52428800 字节。
2024-10-02 08:45:50,476 - root - ERROR - 未配置云上传器，无法分享文件链接。
